export const FOODS_FETCH_SUCCESS = "FOODS_FETCH_SUCCESS";
export const FOODS_FETCH_ERROR = "FOODS_FETCH_ERROR";
export const FOODS_LOADING = "FOODS_LOADING";
export const FOOD_DETAILS_FETCH = "FOOD_DETAILS_FETCH";

export const CATEGORIES_FETCH_SUCCESS = "CATEGORIES_FETCH_SUCCESS";
export const CATEGORIES_FETCH_ERROR = "CATEGORIES_FETCH_ERROR";
export const CATEGORIES_LOADING = "CATEGORIES_LOADING";

export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_TO_CART = "DELETE_TO_CART";
